---
- hosts:
  - system76laptop
  tasks:
  # https://docs.ansible.com/ansible/latest/collections/kubernetes/core/helm_module.html
  - name: Install metallb load balancer
    kubernetes.core.helm:
      release_name: metallb
      chart_ref: metallb/metallb
      release_namespace: metallb-system
      create_namespace: true
      wait: true
  - name: Apply settings for IP address range for load balancer
    ansible.builtin.command: kubectl apply -f /home/carlsonp/src/myhomelab-ansible/playbooks/kubernetes/metallb-values.yml
  - name: Install cert-manager
    kubernetes.core.helm:
      release_name: cert-manager
      chart_ref: jetstack/cert-manager
      release_namespace: cert-manager
      create_namespace: true
      wait: true
      set_values:
      - value: installCRDs=true
        value_type: string
  - name: kubectl apply Traefik dashboard settings
    ansible.builtin.command: kubectl apply -f /home/carlsonp/src/myhomelab-ansible/playbooks/kubernetes/traefik-dashboard-ingress.yml
  - name: kubectl apply Traefik settings
    ansible.builtin.command: kubectl apply -f /home/carlsonp/src/myhomelab-ansible/playbooks/kubernetes/traefik-values.yml
  - name: Install Longhorn
    kubernetes.core.helm:
      release_name: longhorn
      chart_ref: longhorn/longhorn
      release_namespace: longhorn-system
      create_namespace: true
      wait: true
      values_files:
      - /home/carlsonp/src/myhomelab-ansible/playbooks/kubernetes/longhorn-values.yml
  - name: Turn off default storage class and prefer longhorn
    ansible.builtin.command: "kubectl patch storageclass local-path -p '{\"metadata\": {\"annotations\":{\"storageclass.kubernetes.io/is-default-class\":\"false\"}}}'"
  - name: Install Rancher dashboard
    ansible.builtin.command: helm install rancher rancher-stable/rancher --namespace cattle-system --create-namespace  --set hostname=rancher.my.org --set bootstrapPassword=admin
  - name: Make Rancher available through the load balancer
    ansible.builtin.command: kubectl apply -f /home/carlsonp/src/myhomelab-ansible/playbooks/kubernetes/rancher-values.yml -n cattle-system
  - name: Install argo-cd
    kubernetes.core.helm:
      release_name: argo-cd
      chart_ref: argo/argo-cd
      release_namespace: argo-cd
      create_namespace: true
      wait: true
      values_files:
      - /home/carlsonp/src/myhomelab-ansible/playbooks/kubernetes/argo-cd-values.yml
