---
- hosts: ubuntu
  tasks:
  - name: set apt proxy to the local cache mirror
    become: true
    copy:
      dest: /etc/apt/apt.conf.d/00squidproxy
      content: |
        Acquire {
          Retries "0";
          HTTP { Proxy "http://192.168.1.226:3143"; };
        };

  - name: setup Systemd script for automating rclone backups
    become: true
    ansible.builtin.copy:
      src: "{{ playbook_dir }}/../systemd/rclone-backup.service"
      dest: /etc/systemd/system/rclone-backup.service
      mode: 644
  - name: setup Systemd timer for automating rclone backups
    become: true
    ansible.builtin.copy:
      src: "{{ playbook_dir }}/../systemd/rclone-backup.timer"
      dest: /etc/systemd/system/rclone-backup.timer
      mode: 644
  - name: start Systemd rclone backup service
    become: true
    ansible.builtin.systemd:
      name: rclone-backup.service
      state: started
      daemon_reload: yes
      enabled: yes
  - name: start Systemd rclone backup timer
    become: true
    ansible.builtin.systemd:
      name: rclone-backup.timer
      state: started
      daemon_reload: yes
      enabled: yes
  # we want to use our own pihole servers for DNS resolution
  - name: Disable and stop systemd-resolved service
    become: true
    ansible.builtin.systemd:
      name: systemd-resolved
      enabled: false
      state: stopped
  - name: Remove /etc/resolv.conf symlink
    become: true
    ansible.builtin.file:
      path: /etc/resolv.conf
      state: absent
  - name: Create static /etc/resolv.conf
    become: true
    ansible.builtin.copy:
      dest: /etc/resolv.conf
      content: |
        nameserver 192.168.1.226
        nameserver 192.168.1.114
      owner: root
      group: root
      mode: '0644'
