---
- hosts: ubuntu
  tasks:
  - name: set apt proxy to the local cache mirror
    become: true
    copy:
      dest: /etc/apt/apt.conf.d/01proxy
      content: |
        Acquire::HTTP::Proxy "http://192.168.1.226:3142";
        Acquire::HTTPS::Proxy "false";

    