---
- hosts: ubuntu
  vars:
    # 20.04
    ubuntu_codename: focal
  tasks:
  - name: Get DEB architecture
    ansible.builtin.shell: dpkg --print-architecture
    register: deb_architecture # arm64 or amd64
  - name: install common packages
    become: true
    # https://docs.ansible.com/ansible/2.9/modules/apt_module.html#apt-module
    apt:
      name:
        - nano
        - openssh-server
        - aptitude
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        - wget
        - python3
        - python3-pip
        - lsb-release
        - gnupg
        - zip
        - unzip
        - zfsutils-linux
        - build-essential
        - gparted
        - smartmontools
        - vlc
        - gitk
        - git-core
        - git-gui
      state: latest
      update_cache: yes
      install_recommends: yes
  - name: add GPG key for docker
    become: true
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: add docker repository to apt
    become: true
    apt_repository:
      repo: deb [arch={{ deb_architecture }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ubuntu_codename }} stable
      state: present
  - name: install docker via apt
    become: true
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: latest
      update_cache: yes
  - name: make sure docker has started
    become: true
    service:
      name: docker
      state: started
      enabled: yes
  
  # post-install Docker steps
  # https://docs.docker.com/engine/install/linux-postinstall/
  - name: make sure docker group exists
    become: true
    ansible.builtin.group:
      name: docker
      state: present
  - name: add this user to docker group
    become: true
    ansible.builtin.user:
      name: '{{ ansible_user_id }}'
      groups: docker
      append: yes # this ensures it will add-to and not replace all groups

  # install docker-compose
  # https://docs.docker.com/compose/cli-command/#install-on-linux
  - name: create directory for docker-compose
    ansible.builtin.file:
      path: ~/.docker/cli-plugins/
      state: directory
      mode: '0775'
  - name: ansible architecture
    debug:
      msg: "ansible_architecture: {{ ansible_architecture }}" # x86_64 or aarch64
  - name: download and place docker-compose v2 binary
    ansible.builtin.get_url:
      url: https://github.com/docker/compose/releases/latest/download/docker-compose-linux-{{ ansible_architecture }}
      dest: ~/.docker/cli-plugins/docker-compose
      mode: '0775'
  
  # install rclone