---
- hosts: openwrt
  tasks:
  - name: update package listing via opkg
    ansible.builtin.command: opkg update
  - name: install packages via opkg
    ansible.builtin.command: opkg install "{{ item }}"
    loop:
      - luci-ssl
      - nano
      - luci-app-statistics
      - collectd-mod-cpu
      - collectd-mod-interface
      - collectd-mod-memory
      - collectd-mod-ping
      - collectd-mod-rrdtool
      - collectd-mod-wireless
      - luci-app-vnstat
      - luci-app-adblock
  # https://wiki.openwrt.org/doc/howto/secure.access
  # this is now not needed for 21.X releases
  # - name: force HTTPS over HTTP for web login
  #   ansible.builtin.command: uci delete uhttpd.main.listen_http ; uci commit
  # - name: restart http server
  #   ansible.builtin.command: /etc/init.d/uhttpd restart
  # https://oldwiki.archive.openwrt.org/doc/howto/luci_app_statistics
  - name: enable stats tracking
    ansible.builtin.command: /etc/init.d/luci_statistics enable
  - name: enable the monitoring service
    ansible.builtin.command: /etc/init.d/collectd enable
  - name: setup Wifi radios with access key
    ansible.builtin.copy:
      src: ./secrets/wireless
      dest: /etc/config/wireless
      owner: root
      group: root
      mode: u=rw
  - name: firewall rule blocking internet access for cameras and other devices
    ansible.builtin.blockinfile:
      path: /etc/config/firewall
      block: |
        config rule
          list proto 'all'
          option name 'BlockInternet'
          # hs105-1
          list src_ip '192.168.1.147'
          # hs105-2
          list src_ip '192.168.1.200'
          # hs105-3
          list src_ip '192.168.1.188'
          # hs105-4
          list src_ip '192.168.1.172'
          # IP4M-1051W
          list src_ip '192.168.1.111'
          option dest 'wan'
          option target 'REJECT'
          option src 'lan'
  # https://openwrt.org/docs/guide-user/base-system/dhcp
  - name: add Raspberry Pi 4 as DNS provider via pihole
    ansible.builtin.blockinfile:
      path: /etc/config/dhcp
      block: |
        config dhcp 'lan'
          option interface 'lan'
          option start '100'
          option limit '150'
          option leasetime '12h'
          option dhcpv6 'server'
          option ra 'server'
          option ra_management '1'
          # sets pi4 pihole as DNS provider and our backup
          list dhcp_option '6,192.168.1.226,192.168.1.140'
  - name: Add static DHCP mappings to /etc/config/dhcp
    ansible.builtin.blockinfile:
      path: /etc/config/dhcp
      # this mark statement is required otherwise the block will be overwritten on each iteration
      marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
      block: |
        config host
          option mac {{ item.mac }}
          option name {{ item.name }}
          option dns '1'
          option ip {{ item.ip }}
    loop:
      - { mac: '58:47:CA:70:92:C9', name: 'MinisForums', ip: '192.168.1.112' }
      - { mac: 'C8:60:00:A1:C3:6B', name: 'BlueAntec', ip: '192.168.1.138' }
      - { mac: 'D4:5D:64:D4:F0:43', name: 'alienware', ip: '192.168.1.105' }
      - { mac: '20:C1:9B:74:E3:9D', name: 'system76-pc', ip: '192.168.1.124' }
      - { mac: 'B8:27:EB:59:AF:25', name: 'raspberrypi3', ip: '192.168.1.224' }
      - { mac: 'C8:60:00:A1:D7:07', name: 'BlueAntec', ip: '192.168.1.113' }
      - { mac: '98:DA:C4:4A:37:5A', name: 'hs105-1', ip: '192.168.1.147' }
      - { mac: '98:DA:C4:B8:D8:36', name: 'hs105-2', ip: '192.168.1.200' }
      - { mac: '98:DA:C4:4A:26:D6', name: 'hs105-3', ip: '192.168.1.188' }
      - { mac: '00:1A:92:D8:CB:2E', name: 'antec-backup', ip: '192.168.1.140' }
      - { mac: 'DC:A6:32:BD:63:F8', name: 'pifour', ip: '192.168.1.226' }
      - { mac: '84:D8:1B:F4:AF:8C', name: 'hs105-4', ip: '192.168.1.172' }
      - { mac: '9C:8E:CD:22:F0:06', name: 'IP4M-1051W', ip: '192.168.1.111' }
  - name: manual step for cleanup of original dhcp lan entry
    debug:
      msg: "Manually edit /etc/config/dhcp and remove the top block defining - config dhcp 'lan'"
  - name: setup complete, reboot router
    debug:
      msg: "You may now reboot the router"