---
- hosts: ubuntu
  tasks:
  - name: apt update and look for package upgrades
    become: true
    # https://docs.ansible.com/ansible/2.9/modules/apt_module.html#apt-module
    apt:
      upgrade: yes
      update_cache: yes
      install_recommends: yes
  - name: Stat the reboot-required file
    stat:
      path: /var/run/reboot-required
    register: reboot_required
  - name: Show if reboot required
    debug:
      msg: "Reboot is required"
    when: reboot_required.stat.exists
  - name: Show if reboot is not required
    debug:
      msg: "Reboot is NOT required"
    when: not reboot_required.stat.exists
